device:
  name: redfin
  build_id: UP1A.231105.001.B2
  prev_build_id: UP1A.231105.001
  platform_security_patch_level_override: 2023-12-01

platform:
  product_makefile: device/google/redfin/aosp_redfin.mk
  extra_product_makefiles:
    - device/google/redfin/wireless_charger/wireless_charger.mk

includes:
  - common/gen5pixel.yml

filters:
  sepolicy_dirs:
    match:
      - device/google/redbull-sepolicy/system_ext/private
  files:
    match:
      - vendor/etc/vintf/manifest/manifest_wifi_ext.xml
      - vendor/etc/vintf/manifest/manifest_wifi_ext_aidl.xml
      - vendor/bin/gpu_counter_producer
      - system/etc/vintf/manifest/hwservicemanager.xml
      - system/etc/init/hwservicemanager.rc
      - system/etc/vintf/manifest/android.hidl.allocator@1.0-service.xml
      - system/etc/init/android.hidl.allocator@1.0-service.rc
      - system/bin/hw/android.hidl.allocator@1.0-service
      - system/lib64/libclcore_neon.bc
      - system/framework/locksettings.jar
      - system_ext/priv-app/AccessibilityMenu/AccessibilityMenu.apk
      - system/bin/badblocks
      - product/app/PixelCameraServicesRedfin/PixelCameraServicesRedfin.apk
      # dont build OMX codecs
      # https://android-review.googlesource.com/c/platform/frameworks/av/+/2898992
      - vendor/lib/libstagefright_soft_vpxdec.so
      - vendor/lib/libstagefright_soft_mp3dec.so
      - vendor/lib/libstagefright_soft_avcenc.so
      - vendor/lib/libstagefright_soft_mpeg2dec.so
      - vendor/lib/libstagefright_soft_mpeg4dec.so
      - vendor/lib/libstagefright_soft_amrdec.so
      - vendor/lib/libstagefright_soft_opusdec.so
      - vendor/lib/libstagefright_soft_amrwbenc.so
      - vendor/lib/libstagefright_soft_amrnbenc.so
      - vendor/lib/libstagefright_soft_rawdec.so
      - vendor/lib/libstagefright_soft_flacdec.so
      - vendor/lib/libstagefright_soft_aacenc.so
      - vendor/lib/libstagefright_soft_mpeg4enc.so
      - vendor/lib/libstagefright_soft_flacenc.so
      - vendor/lib/libstagefright_soft_vorbisdec.so
      - vendor/lib/libstagefright_soft_avcdec.so
      - vendor/lib/libstagefright_soft_aacdec.so
      - vendor/lib/libstagefright_soft_g711dec.so
      - vendor/lib/libstagefright_soft_vpxenc.so
      - vendor/lib/libstagefright_soft_gsmdec.so
      - vendor/lib/libstagefright_soft_hevcdec.so

  props:
    match:
      - ro.vendor.camera.extensions.package
      - ro.vendor.camera.extensions.service
