device:
  name: tangorpro
  build_id: TQ3A.230805.001.B1
  prev_build_id: TQ3A.230705.001.B4

platform:
  product_makefile: device/google/tangorpro/aosp_tangorpro.mk

includes:
  - common/gen7pixel.yml

filters:
  overlay_files:
    match:
      # aapt2 parsing bug encountered within adevtool
      - DockSetup__auto_generated_rro_product.apk
      - Flipendo__auto_generated_rro_product.apk
      - SettingsGoogle__auto_generated_rro_product.apk
      - StorageManagerGoogle__auto_generated_rro_product.apk
      - SystemUITitan__auto_generated_rro_product.apk
      - Traceur__auto_generated_rro_product.apk
