type: device-list

devices:
  - tangorpro.yml
  - lynx.yml
  - cheetah.yml
  - panther.yml
  - bluejay.yml
  - raven.yml
  - oriole.yml
  - barbet.yml
  - redfin.yml
  - bramble.yml
  - sunfish.yml
  - coral.yml
  - flame.yml
