platform:
  sepolicy_dirs:
    - device/google/sunfish-sepolicy

includes:
  - pixel.yml

filters:
  files:
    match:
      - vendor/etc/vintf/manifest/manifest_wifi_ext.xml

  dep_files:
    match:
      # system/chre/Android.mk: error: "chre (EXECUTABLES android-arm64) missing libadsprpc (SHARED_LIBRARIES android-arm64)"
      - vendor/lib/libadsprpc.so
      - vendor/lib64/libadsprpc.so

  overlay_files:
    match:
      # aapt2 parsing bug encountered within adevtool
      - HbmSVManager__auto_generated_rro_vendor.apk

  files:
    prefix:
      # APEX
      - vendor/apex/com.android.vibrator.sunfish.apex
