platform:
  sepolicy_dirs:
    - device/google/coral-sepolicy

includes:
  - pixel.yml

filters:
  files:
    match:
      - vendor/etc/vintf/manifest/manifest_wifi_ext.xml
      - vendor/bin/hw/android.hardware.nfc@1.2-service.st
      - vendor/etc/init/android.hardware.nfc@1.2-service.st.rc

  dep_files:
    match:
      # system/chre/Android.mk: error: "chre (EXECUTABLES android-arm64) missing libsdsprpc (SHARED_LIBRARIES android-arm64)"
      - vendor/lib/libsdsprpc.so
      - vendor/lib64/libsdsprpc.so
