device:
  vendor: google_devices

includes:
  - file-removal.yml
  - overlay-removal.yml
  - removal.yml

platform:
  sepolicy_dirs:
    - hardware/google/pixel-sepolicy

filters:
  dep_files:
    prefix:
      # Protobufs for inline carrier extraction
      - product/etc/CarrierSettings/
  deprivileged_apks:
    prefix:
      - system_ext/priv-app/PixelNfc/

apk_max_version_requirements:
  # EuiccSupportPixel (updater of secure element firmware)
  com.google.euiccpixel: 17515
