platform:
  sepolicy_dirs:
    - device/google/coral-sepolicy

includes:
  - pixel-qcom.yml

device:
  build_id: TP1A.221005.002.B2
  prev_build_id: TP1A.221005.002
  platform_security_patch_level_override: 2022-11-01

filters:
  files:
    match:
      - vendor/etc/vintf/manifest/manifest_wifi_ext.xml
      - vendor/bin/hw/android.hardware.nfc@1.2-service.st
      - vendor/etc/init/android.hardware.nfc@1.2-service.st.rc

  dep_files:
    match:
      # system/chre/Android.mk: error: "chre (EXECUTABLES android-arm64) missing libsdsprpc (SHARED_LIBRARIES android-arm64)"
      - vendor/lib/libsdsprpc.so
      - vendor/lib64/libsdsprpc.so
