platform:
  sepolicy_dirs:
    - device/google/sunfish-sepolicy

includes:
  - pixel-qcom.yml

filters:
  dep_files:
    match:
      # system/chre/Android.mk: error: "chre (EXECUTABLES android-arm64) missing libadsprpc (SHARED_LIBRARIES android-arm64)"
      - vendor/lib/libadsprpc.so
      - vendor/lib64/libadsprpc.so

  files:
    match:
      - vendor/etc/vintf/manifest/manifest_wifi_ext.xml

    prefix:
      # APEX
      - vendor/apex/com.android.vibrator.sunfish.apex
