platform:
  sepolicy_dirs:
    - device/google/gs101-sepolicy

device:
  build_id: AP1A.240505.004

includes:
  - pixel.yml
  - gs.yml

filters:
  dep_files:
    match:
      # external/android-nn-driver/Android.mk: error: "android.hardware.neuralnetworks@1.0-service-armnn (EXECUTABLES android-arm64) missing libOpenCL (SHARED_LIBRARIES android-arm64)"
      - vendor/lib/libOpenCL.so
      - vendor/lib64/libOpenCL.so
  files:
    match:
      # Remove Google screw-up with USB hardware debugging
      - vendor/bin/uci_daemon
      - vendor/etc/init/usb-cdc.rc
      # Remove fstab FIPS variant which we have disabled fully
      - vendor/etc/fstab.gs101-fips
