platform:
  sepolicy_dirs:
    - device/google/gs-common

  vendor_linker_config:
    # TODO: look into generating this automatically, at least for APEXes, by unpacking them and checking apex_manifest.pb
    provideLibs:
      # used by com.google.pixel.camera.hal.apex
      - lib_aion_buffer.so
      - libedgetpu_client.google.so
      - libedgetpu_tachyon.google.so
      - libedgetpu_util.so
      - libgxp.so
      # used by com.google.android.widevine.apex
      - liboemcrypto.so
