includes:
  - file-removal.yml
  - overlay-removal.yml
  - removal.yml

device:
  vendor: google_devices
  system_fs_type: ext4

  build_id: TQ3A.230805.001
  prev_build_id: TQ3A.230705.001

platform:
  sepolicy_dirs:
    - hardware/google/pixel-sepolicy

filters:
  deprivileged_apks:
    prefix:
      - system_ext/priv-app/PixelNfc/
