includes:
  - file-removal.yml
  - overlay-removal.yml
  - removal.yml

device:
  vendor: google_devices
  system_fs_type: ext4
  kernel_repo_url: https://android.googlesource.com/kernel/gs

  build_id: AP1A.240405.002
  prev_build_id: AP1A.240305.019.A1

platform:
  sepolicy_dirs:
    - hardware/google/pixel-sepolicy

filters:
  deprivileged_apks:
    prefix:
      - system_ext/priv-app/PixelNfc/
