includes:
  - file-removal.yml
  - overlay-removal.yml
  - removal.yml

device:
  vendor: google_devices
  build_id: TQ3A.230805.001
  prev_build_id: TQ3A.230705.001

platform:
  sepolicy_dirs:
    - hardware/google/pixel-sepolicy

filters:
  dep_files:
    prefix:
      # Protobufs for inline carrier extraction
      - product/etc/CarrierSettings/
  deprivileged_apks:
    prefix:
      - system_ext/priv-app/PixelNfc/
